name: Bug Report
description: Something isn't working quite right.
labels: [bug]
body:
- type: markdown
  attributes:
    value: |
      Bug reports should only be used for reporting issues with how the software works, which you are also able to reproduce.
